
include("vector.jl")
include("map/realization.jl")
# include("map/deserialization.jl")
include("unfold/realization.jl")
# include("unfold/deserialization.jl")
# include("switch/realization.jl")
# include("switch/deserialization.jl")
# include("recurse/realization.jl")
# include("recurse/deserialization.jl")