name = "GenSerialization"
uuid = "21e319bb-9f6a-4cc8-b556-663507cd964d"
authors = ["Ian Limarta"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
